<?php

    include('connection.php');

    session_start();
    
    /*
     * The only items that need to be passed to the DB to create a new ticket are:
     *      priority
     *      description
     *      created_by
     * 
     * The ticket_id, date_created, assigned_to, and status values are auto
     * generated by MySQL.
     * 
     * The created_by is going to use the session's User_ID that is generated when
     * the user logs into the system.
     * 
     * Priority and description are generated when the user submits the new ticket in
     * user_create_ticket.php
    */

    $username = $_SESSION['User_ID'];
    $priority = mysqli_real_escape_string($con, $_REQUEST['levels']);
    $description = mysqli_real_escape_string($con, $_REQUEST['description']);

    $sql = "INSERT INTO tickets (priority, description, created_by) 
        VALUES ('$priority', '$description', '$username')";
    
    if(mysqli_query($con, $sql)) {

        /*
         * Ideally, the user will receive a pop-up that the ticket was successfully created
         * and THEN be re-directed to the user main page. I would also prefer to have this 
         * be where a confirmation email is sent, but I don't have dummy emails ready to go.
        */
        echo '<script>alert("Ticket successfully created")</script>';
        header("refresh:0; url=insert_redirect.php");
        
    } else {

        echo '<script>alert("ERROR: Unable to execute $sql. " . mysqli_error($con))</script>';
        header("refresh:0; url=insert_redirect.php");
    }

?>